In [13]:
# Importing Packages
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.datasets import load_iris



In [16]:
# Loading Dataset
data = load_iris()
print(data)



{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [17]:
#So, the Classes are - [ 0 , 1 , 2 ] instead of ['setosa' 'versicolor' 'virginica'].
# Three parts: data, target, target_names
x = data.data
y = data.target
z = data.target_names
print(data.feature_names)
print(x[0]) #first observation

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[5.1 3.5 1.4 0.2]


In [18]:
# Split Dataset
from sklearn.model_selection import train_test_split
x_train, x_test,  y_train, y_test = train_test_split(x, y, test_size=0.3) #100 examples, training part 70, test part 30

In [19]:
# Data Shape
print(x_train.shape) 
print(x_test.shape)

(105, 4)
(45, 4)


In [20]:
# Building the Model
model= Sequential()
model.add(Dense(100,input_shape=(4,), activation="relu")) #100 neurons, relu -value = 0 else same.
model.add(Dense(3, activation='softmax')) #3 classes

In [21]:
# Compile the Model
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"]) #stochastic gradient descent method

In [22]:
# Fit the Model
model.fit(x_train,y_train, epochs=20)

Epoch 1/20
4/4 [==============================] - 0s 2ms/step - loss: 1.2979 - accuracy: 0.3429
Epoch 2/20
4/4 [==============================] - 0s 2ms/step - loss: 1.1312 - accuracy: 0.3429
Epoch 3/20
4/4 [==============================] - 0s 1ms/step - loss: 0.9954 - accuracy: 0.3429
Epoch 4/20
4/4 [==============================] - 0s 2ms/step - loss: 0.9128 - accuracy: 0.5429
Epoch 5/20
4/4 [==============================] - 0s 997us/step - loss: 0.8596 - accuracy: 0.7524
Epoch 6/20
4/4 [==============================] - 0s 1ms/step - loss: 0.8187 - accuracy: 0.6571
Epoch 7/20
4/4 [==============================] - 0s 2ms/step - loss: 0.7781 - accuracy: 0.6571
Epoch 8/20
4/4 [==============================] - 0s 2ms/step - loss: 0.7419 - accuracy: 0.7048
Epoch 9/20
4/4 [==============================] - 0s 2ms/step - loss: 0.7146 - accuracy: 0.8857
Epoch 10/20
4/4 [==============================] - 0s 1ms/step - loss: 0.6898 - accuracy: 0.9619
Epoch 11/20
4/4 [====================

In [23]:
# Evaluate the Model
model.evaluate(x_test, y_test)

2/2 [==============================] - 0s 2ms/step - loss: 0.5529 - accuracy: 0.9111


[0.5529444217681885, 0.9111111164093018]

In [24]:
# Predict for the first 10 Observations
pred=model.predict(x_test[:10])
print(pred)

1/1 [==============================] - 0s 33ms/step
[[0.03464804 0.4049114  0.5604406 ]
 [0.1297341  0.49889383 0.37137216]
 [0.07718963 0.4666324  0.45617798]
 [0.8612898  0.11571698 0.02299317]
 [0.06510223 0.46907553 0.46582225]
 [0.0934725  0.47186026 0.4346672 ]
 [0.2470048  0.47158572 0.28140956]
 [0.04296407 0.44522884 0.5118071 ]
 [0.82651305 0.14484291 0.02864407]
 [0.71997637 0.21778959 0.06223405]]


In [27]:
p=np.argmax(pred, axis=1)
print(p)
print(y_test[:10])

[2 1 1 0 1 1 1 2 0 0]
[2 1 1 0 2 1 1 2 0 0]


In [28]:
# Prediction Result
for i in p:
  print("Predicted-Class: {},   Name: {}".format(i,z[i]))

Predicted-Class: 2,   Name: virginica
Predicted-Class: 1,   Name: versicolor
Predicted-Class: 1,   Name: versicolor
Predicted-Class: 0,   Name: setosa
Predicted-Class: 1,   Name: versicolor
Predicted-Class: 1,   Name: versicolor
Predicted-Class: 1,   Name: versicolor
Predicted-Class: 2,   Name: virginica
Predicted-Class: 0,   Name: setosa
Predicted-Class: 0,   Name: setosa
